name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Initialize database
      run: |
        python -c "
        import sqlite3
        from DAL import createDatabase
        createDatabase()
        conn = sqlite3.connect('projects.db')
        cursor = conn.cursor()
        cursor.execute('SELECT name FROM sqlite_master WHERE type=\"table\" AND name=\"projects\"')
        result = cursor.fetchone()
        if result:
            print('✅ Database table created successfully')
        else:
            print('❌ Database table creation failed')
            exit(1)
        conn.close()
        "
    
    - name: Run tests
      run: |
        pytest test_database.py test_projects.py -v --cov=. --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t bryant-website:latest .
    
    - name: Test Docker container
      run: |
        docker run -d -p 8000:8000 --name test-container bryant-website:latest
        sleep 10
        curl -f http://localhost:8000/ || exit 1
        docker stop test-container
        docker rm test-container
